name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      llama_cpp_version: "master"
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    with:
      llama_cpp_version: "master"
    secrets: inherit
